### ISSUE TITLE
Too many scripts?

### ISSUE THREAD

**Issue by meodai** [caillou/caillou.ch#3]
<img width="667" alt="Screenshot 2021-05-18 at 15 02 49" src="https://user-images.githubusercontent.com/608386/118655949-53bc1f00-b7ea-11eb-8cfd-497bc71a0f94.png">

Feels like a lot or such a simple looking page.

**Comment by caillou** [comment]
These scripts are not essential for the rendering of the page. I have chosen to go on the `Next.js` way and leave them in.
