### ISSUE TITLE
Page is too heavy. (long loading times)

### ISSUE THREAD

**Issue by meodai** [caillou/caillou.ch#4]
https://caillou.ch/_next/image?url=%2Fpierre-hq.jpg&w=1080&q=75

is 27MB!!!!

Took ages to load, because I was not in the best wifi spot. 1 Optimage iteration gets it down to 6.4 MB I would compress it further though.
![pierre-hq](https://user-images.githubusercontent.com/608386/118656461-d644de80-b7ea-11eb-992a-afb5881238c1.jpg)

**Comment by caillou** [comment]
Interesting! This should be resized to a 1.7mb webp. Will investigate!!!

**Comment by caillou** [comment]
Moved away from `Next/Image` and using `<picture>` with `<source>` and `srcSet` while pre-rendering loads of images on build. Performace should now be stellar.

**Comment by meodai** [comment]
it is instantly loading now
